# Generated by Django 3.2.7 on 2023-09-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_red_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='red_code',
            new_name='ref_code',
        ),
    ]
